# Required
[[plugins]]
repo = 'Shougo/dein.vim'

# General enhancements
[[plugins]]
repo = 'tpope/vim-abolish'
[[plugins]]
repo = 'tpope/vim-vinegar'
[[plugins]]
repo = 'tpope/vim-characterize'
[[plugins]]
repo = 'tpope/vim-commentary'
[[plugins]]
repo = 'tpope/vim-dispatch'
[[plugins]]
repo = 'tpope/vim-eunuch'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tpope/vim-ragtag'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tpope/vim-scriptease'
[[plugins]]
repo = 'tpope/vim-sensible'
[[plugins]]
repo = 'tpope/vim-sleuth'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-tbone'
[[plugins]]
repo = 'tpope/vim-unimpaired'
[[plugins]]
repo = 'tpope/vim-projectile'
[[plugins]]
repo = 'tpope/vim-obsession'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'nvie/vim-flake8'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
[[plugins]]
repo = 'KohPoll/vim-less'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'mileszs/ack.vim'
[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = 'junegunn/vim-easy-align'
# [[plugins]] Removed since this doesn't search new files.
# repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'jeffkreeftmeijer/vim-numbertoggle'

# Snippets
[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'
[[plugins]]
repo = 'tomtom/tlib_vim'
# [[plugins]] Removed since it overlaps with ultisnips
# repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'SirVer/ultisnips'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'othree/html5.vim'

# Play enhancements
[[plugins]]
repo = 'gre/play2vim'


# Djando enhancements
[[plugins]]
repo = 'tweekmonster/django-plus.vim'

# Rails enhancements
[[plugins]]
repo = 'tpope/vim-bundler'
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'tpope/vim-rake'
[[plugins]]
repo = 'vim-ruby/vim-ruby'
[[plugins]]

# Markdown; somehow these plugins couldn't not be installed here.
# [[plugins]]
# repo = 'kannokanno/previm'
# [[plugins]]
# repo = 'tyru/open-browser.vim'
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
